config/routes.rb
Torvguide::Application.routes.draw do
  get "main/index"

  match 'site_variant' => 'main#variant', :as => :variant

  match "/application.manifest" => TORV_OFFLINE unless Rails.env.development?

  resources :media_roots
  resources :philes, :path => "files" do
    resource :episode
    resource :movie
    resource :show
  end

  resources :shows do
    collection do
      get 'recent'
    end
    resources :show_names
    resources :episodes
    resources :philes, :path => "files"
  end

  resources :episodes do
    resource :phile, :path => "file"
    member do
      post :watch
      post :unwatch
    end
    collection do
      get :popup
    end
  end

  root :to => "main#index"

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def variant
    cookies[:site_variant] = params[:variant]
    session[:mobile_view] = case params[:variant]
                              when nil, "", "normal" then false
                              else true
                            end
    redirect_to :root
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/episodes.html.erb
<style type="text/css">
  table { width: 100%; }
  td.unparsed { font-style: italic; }
  tr.group {
      background-color: #2f4f4f;
      color: white;
  }
  tr.group td {
      padding-right: 40px;
      padding-top: 10px;
      padding-bottom: 10px;
      text-align: right;
      margin: 8px;
  }
  td.title { text-align: right; }

</style>
<table>
<%- groupify(@episodes, Proc.new {|ep| ep.aired_at || ep.phile.file_created_at }).each do |pair|
    (group, episodes) = pair
-%>
<tr class="group"><td colspan="4">Aired less than <%= time_ago_in_words group %> ago</td></tr>
<%-
    episodes.each do |episode|
        show = episode.show
-%>
<tr>
      <td class="parsed"><%= show.name[0..30] %></td><td><%= episode.season %></td><td><%= episode.number %></td>
      <td class="title"><%= episode.title %></td>
</tr>
      <%- end -%>
  <%- end -%>
</table>

app/views/main/index.html.haml
%p
  Welcome to the TV list!
  %p
    %p Please choose Files, Shows, or Episodes from the menu above.
    = link_to "JQ Mobile Site", variant_path(:variant => "iphone")
    = link_to "Sencha Site", "/tvs/index.html"

app/views/main/index.mobile.haml
%ul{"data-dividertheme" => "b", "data-inset" => "true", "data-role" => "listview", "data-theme" => "c"}
  %li= link_to "Episodes", :episodes
  / <li><haml:loud> link_to &amp;quot;Files&amp;quot;, :philes </haml:loud></li>
  %li= link_to "Shows", :shows