config/routes.rb
Torvguide::Application.routes.draw do
  get "main/index"

  match 'site_variant' => 'main#variant', :as => :variant

  match "/application.manifest" => TORV_OFFLINE unless Rails.env.development?

  resources :media_roots
  resources :philes, :path => "files" do
    resource :episode
    resource :movie
    resource :show
  end

  resources :shows do
    collection do
      get 'recent'
    end
    resources :show_names
    resources :episodes
    resources :philes, :path => "files"
  end

  resources :episodes do
    resource :phile, :path => "file"
    member do
      post :watch
      post :unwatch
    end
    collection do
      get :popup
    end
  end

  root :to => "main#index"

end

app/models/media_root.rb
require_dependency "db_lockable"

class MediaRoot < ActiveRecord::Base
  has_many :philes, :dependent => :destroy do
    def stale
      where("updated_at < ?", proxy_owner.scanned_at.utc)
    end
  end

  scope :active, :conditions => {:active => true} 
  scope :inactive, :conditions => {:active => false}

  before_validation :load_filesystem_data

  validates_uniqueness_of :path

  include DBLockable

  class << self
    def find_root_for_path(path)
      roots = MediaRoot.active.sort {|a,b| b.path.size <=> a.path.size }
      roots.each do |root|
        return root if root.contains_path?(path)
      end
      nil
    end
  end

  def add_all_files
    list = []
    Find.find(path) do |path|
      base = File.basename(path)
      if base[0..0] == "."
        Find.prune if FileTest.directory?(path)
        next
      end

      next if FileTest.symlink?(path) || FileTest.directory?(path) || ! Phile.is_movie?(base)
      if phile=Phile.find_by_path(path)
        phile.mark_alive!
      else
        Phile.from_path(path, self).save!
      end

      next
    end
  end

  def scan
    start = Time.now.utc

    # implicit Transaction here
    with_lock do
      self.update_attributes :scanned_at => start

      add_all_files

      philes.where("updated_at < ?", start).each do |phile|
        phile.mark_deleted!
      end

      # do the heavy lifting of turning philes into episodes/movies
      philes.unresolved.not_processed_recently.each do |phile|
        phile.process
      end

    end
  end

  def scan_if_scheduled
    scan if self.ready_to_scan?
  end

  def ready_to_scan?
    !self.scanned_at or self.scanned_at + self.scan_period < Time.now
  end

  def contains_path?(path)
    path.start_with? self.path
  end

  protected

  # get real-world state about this
  def load_filesystem_data
    
  end

end

app/controllers/media_roots_controller.rb
class MediaRootsController < ApplicationController
  inherit_resources
  respond_to :html, :json, :js, :xml

end

app/views/media_roots/_form.html.haml
%table
  - form_for resource, :as => :media_root, :url => media_root_path(resource) do |f|
    - if resource.errors.any?
      %tr
        %td{:colspan => "2"}
          %h2
            = pluralize(resource.errors.count, "error")
            prohibited this from being saved:
          %ul
            - resource.errors.full_messages.each do |msg|
              %li= msg
    - resource.attributes.each do |a|
      %tr
        %td= a[0]
        %td= f.text_field a[0].to_sym
    %tr
      %td{:colspan => "2"}= f.submit

app/views/media_roots/edit.html.haml
= render "form"
%p= link_to "Show", media_root_path(resource)
%p= link_to "Back", polymorphic_path(controller_name)

app/views/media_roots/index.html.haml
%p= link_to "New", new_media_root_path
- if collection.any?
  %table
    %thead
      %tr
        - collection.first.attributes.each do |a|
          %th= a[0]
    %tbody
      - collection.each do |r|
        %tr
          - r.attributes.each do |a|
            %td= a[1]
          %td= link_to "Show", media_root_path(r)
          %td= link_to "Edit", edit_media_root_path(r)
          %td= link_to "Destroy", media_root_path(r), :confirm => 'Are you sure?', :method => :delete

app/views/media_roots/new.html.haml
= render "form"
%p= link_to "Back", polymorphic_path(controller_name)

app/views/media_roots/show.html.haml
%table
  - resource.attributes.each do |a|
    %tr
      %th= a[0]
      %td= a[1]
%p= link_to "Edit", edit_media_root_path(resource)
%p= link_to "Back", polymorphic_path(controller_name)