config/routes.rb
Torvguide::Application.routes.draw do
  get "main/index"

  match 'site_variant' => 'main#variant', :as => :variant

  match "/application.manifest" => TORV_OFFLINE unless Rails.env.development?

  resources :media_roots
  resources :philes, :path => "files" do
    resource :episode
    resource :movie
    resource :show
  end

  resources :shows do
    collection do
      get 'recent'
    end
    resources :show_names
    resources :episodes
    resources :philes, :path => "files"
  end

  resources :episodes do
    resource :phile, :path => "file"
    member do
      post :watch
      post :unwatch
    end
    collection do
      get :popup
    end
  end

  root :to => "main#index"

end

app/models/episode.rb
require_dependency 'groupify'
``
class Episode < ActiveRecord::Base
  belongs_to :show, :counter_cache => true
  belongs_to :phile
  has_one    :seen, :dependent => :destroy

  validates_uniqueness_of :number, :scope => [:show_id, :season]
  validates_uniqueness_of :unique_number, :scope => [:show_id],
                          :allow_nil => true, :allow_blank => true
  

  # XXX - temp hack until we figure out seen state
  scope :unseen, :conditions => "seen_at is null"

  scope :recent, :conditions => ["aired_at >= ?", 3.months.ago]

  def mark_seen!
    update_attributes :seen_at => Time.now.utc
    show.update_cached_values
  end

  def mark_unseen!
    update_attributes :seen_at => nil
    show.update_cached_values
  end

  def valid_numbers?
    ! (season.blank? || season.to_s == "0" || number.blank? || number.to_s == "0")
  end

  def show_name
    show.name
  end

  # XXX: this is so very wrong
  def time_category
    # ActionController::Base.helpers.time_ago_in_words Groupify.groupify([self], Proc.new {|ep| ep.aired_at || ep.phile.file_created_at })[0][0]
    ActionController::Base.helpers.time_ago_in_words self.aired_at
  end

  def as_json(options={})
    serializable_hash( :methods => [:show_name, :time_category], :include =>[:show])
  end
end

app/controllers/episodes_controller.rb
require_dependency 'meta_searchable'

class EpisodesController < ApplicationController
  inherit_resources
  respond_to :html, :json, :js, :xml, :mobile
  
  belongs_to :show, :optional => true
  # belongs_to :phile, :singleton => true, :optional => true



  has_scope :recent

  before_filter { @title = "Episodes" }

  # include MetaSearchable

#  def index
#    collection
#    respond_to do |fmt|
#      fmt.mobile { render }
#      fmt.xml { render :xml => collection }
#      fmt.json { render :json => collection.to_json(:include => [:show]) }
#      fmt.html
#    end
#  end

  def popup
    
  end

  def watch
    resource.mark_seen!
    respond_to do |fmt|
      fmt.html { redirect_to :episodes }
      fmt.json { head :code => 200 }
      fmt.js
    end
  end

  def unwatch
    resource.mark_unseen!
    respond_to do |fmt|
      fmt.html { redirect_to :episodes }
      fmt.json { head :code => 200 }
      fmt.js
    end
  end


  protected

  def collection
    base = end_of_association_chain
    base = base.unseen unless params[:seen] || params[:all]
    if ! @show
      base = base.where("aired_at >= ?", 6.months.ago)
    end

    # XXX - hack to work around jQuery Mobile crashes
    if in_mobile_view?
      base = base.limit(80)
    end
    @episodes ||= base.order("aired_at desc").includes([:show, :phile])
  end
end

app/views/episodes/_episode.html.haml
- show = episode.show
%tr{:class => episode.seen_at ? 'seen' : 'unseen', :id => "episode_#{episode.id}"}
  %td.parsed= link_to show.name[0..30], show_episodes_path(show)
  %td= episode.season
  %td= episode.number
  %td.action= state_button(episode)
  %td.title= link_to episode.title, episode_path(episode)

app/views/episodes/_episode.mobile.haml
- show = episode.show
- click_url = episode_path(episode)
%li.episode.clickable{"data-episode-id" => episode.id, "data-show-id" => episode.show_id, :href => click_url}
  %h3
    = link_to_if false, show.name[0..30], show_episodes_path(show)
  %p
    %strong= link_to_if false, episode.title, episode_path(episode)
  %p= episode.overview
  %p.ui-li-aside
    = episode.season
    \- #{episode.number}

app/views/episodes/index.html.haml
%ul.horizontal_menu
  %li= link_to "All", episodes_path(:all => true)
  %li= link_to "Unwatched", episodes_path
%hr/
%table#episode-list
  - groupify(collection, Proc.new {|ep| ep.aired_at || ep.phile.file_created_at }).each do |pair|
    - (group, episodes) = pair
    %tr.group
      %td{:colspan => "5"}
        Aired less than #{time_ago_in_words group} ago
    = render :partial => "episode", :collection => episodes

app/views/episodes/index.mobile.haml
-# @title = "Episodes for #{@show.name}" if @show
%ul{"data-role" => "listview", "data-theme" => "d"}
  - groupify(collection, Proc.new {|ep| ep.aired_at || ep.phile.file_created_at }).each do |pair|
    - (group, episodes) = pair
    %li{"data-role" => "list-divider"}
      Aired less than #{time_ago_in_words group} ago
    = render :partial => "episode", :collection => episodes

app/views/episodes/popup.mobile.haml
%div{"data-role" => "page"}
  %div{"data-position" => "inline", "data-role" => "header", "data-theme" => "d"}
    %h1 Dialog
  %div{"data-role" => "content", "data-theme" => "c", "data-widget" => "dialog"}
    %h1 Delete page?
    %p
      This is a regular page, styled as a dialog. To create a dialog, just link to a normal page and include a transition and
      %code data-rel="dialog"
      attribute.
    %a{"data-role" => "button", "data-theme" => "b", :href => "/"} Sounds good
    %a{"data-magic-link" => "cancel", "data-role" => "button", "data-theme" => "c", :href => "#"} Cancel

app/views/episodes/seen.js.erb
$('#episode_<%= resource.id %>').hide();

app/views/episodes/show.mobile.haml
- episode = resource
- show = episode.show
%h1= link_to show.name[0..30], show_episodes_path(show)
%p
  Season #{episode.season}, Episode #{episode.number}
%p
  %strong= episode.title
%h3 Overview
%p= episode.overview
%div{"data-role" => "fieldcontain"}
  %select{"data-episode-id" => episode.id, "data-role" => "slider", :id => "watched_#{episode.id}", :name => "watched"}
    %option{:value => "off"} Unwatched
    %option{:selected => "", :value => "on"} Watched
%div
  %a{:href => "/episodes/popup"} Mark Watched

app/views/episodes/unwatch.js.erb
jQuery("#episode_<%= resource.id %>").
        replaceWith("<%= escape_javascript(render :partial => "episode", :object => resource) %>");

app/views/episodes/watch.js.erb
jQuery("#episode_<%= resource.id %>").
        replaceWith("<%= escape_javascript(render :partial => "episode", :object => resource) %>");