config/routes.rb
Torvguide::Application.routes.draw do
  get "main/index"

  match 'site_variant' => 'main#variant', :as => :variant

  match "/application.manifest" => TORV_OFFLINE unless Rails.env.development?

  resources :media_roots
  resources :philes, :path => "files" do
    resource :episode
    resource :movie
    resource :show
  end

  resources :shows do
    collection do
      get 'recent'
    end
    resources :show_names
    resources :episodes
    resources :philes, :path => "files"
  end

  resources :episodes do
    resource :phile, :path => "file"
    member do
      post :watch
      post :unwatch
    end
    collection do
      get :popup
    end
  end

  root :to => "main#index"

end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :episodes, :dependent => :destroy do
    def latest
      order("season desc, number desc").limit(1).first
    end
  end

  has_many :show_names, :dependent => :destroy
  has_many :philes, :through => :episodes

  scope :recent, lambda { active_since(3.months.ago) }

  before_save :update_aliases

  validates_uniqueness_of  :name
  validates_uniqueness_of  :sortable_name
  validates_uniqueness_of  :tvdb_id, :allow_nil => true, :allow_blank => true
  validates_uniqueness_of  :url, :allow_nil => true, :allow_blank => true

  class << self
    def active_since(date)
      ids = Show.find_by_sql("select s.id from shows as s
join episodes as e on e.show_id = s.id
group by s.id
having max(aired_at) > '#{date}'
order by max(aired_at) desc")
      Show.where(:id => ids)
    end


    def make_sortable_string(string)
      string = string.titleize
      ["A", "An", "The"].each do |word|
        if string.start_with? "#{word} "
          string = string[word.length+1..-1] + ", #{word}"
          break
        end
      end
      string.downcase
    end

    def find_from_string(string)
      find(:first, :conditions => ["LOWER(name) = ?", string.downcase]) ||
              find_by_sortable_name(make_sortable_string(string)) || ShowName.find_best_candidate(string)
    end
  end

  def update_aliases
    if name_changed? || new_record?
      make_aliases
    end
  end

  def make_aliases
    self.sortable_name = Show.make_sortable_string(name)
    # ShowName.populate_aliases(self, self.name)
  end

  def has_alias?(string, process=nil)
    base = self.show_names
    if process
      base = base.where("process = ?", process)
    else
      return true if name.downcase == string.downcase || sortable_name.downcase == string.downcase
    end
    base.where("LOWER(name) = ?", string.downcase).count > 0
  end

  def episode(season, number)
    self.episodes.where("season = ? and number = ?", season, number).first
  end

  def add_episode(season, number, title = nil)
    epi = self.episodes.find_or_initialize_by_season_and_number :season => season, :number => number
    if epi.new_record?
      CentralTVDatabase.new.add_episode_metadata(epi)
      epi.title ||= title
      epi.save!
    end

    epi
  end

  def update_cached_values
    latest = episodes.order("aired_at desc").limit(1).first
    latest_unwatched = episodes.unseen.order("aired_at desc").limit(1).first
    update_attributes :unwatched_episode_count => episodes.unseen.count,
                      :episodes_count => episodes.count,
                      :latest_episode_at => latest ? (latest.aired_at || latest.created_at) : nil,
                      :latest_unwatched_episode_at => latest_unwatched ? (latest_unwatched.aired_at || latest_unwatched.created_at) : nil

  end
end

app/controllers/shows_controller.rb
require_dependency 'meta_searchable'

class ShowsController < ApplicationController
  inherit_resources
  respond_to :html, :json, :js, :xml

  has_scope :recent

  include MetaSearchable

  protected

  def collection
    if ! @shows
      col = end_of_association_chain
      unless params[:search] && params[:search][:meta_sort]
        col = col.order("sortable_name asc")
      end
      @shows = col
    end
    @shows
  end
end

app/views/shows/_search_results.html.haml
= render :partial => "show", :collection => search_results.select {|show| show.episodes.size > 0}

app/views/shows/_show.html.haml
%tr
  %td= link_to show.name, show
  %td= link_to show.unwatched_episode_count, show_episodes_path(show, :all => true)
  %td= show.latest_unwatched_episode_at  ? time_ago_in_words(show.latest_unwatched_episode_at) : "NONE"

app/views/shows/_show.mobile.haml
%li.show.clickable{"data-show-id" => show.id, :href => show_episodes_path(show)}
  %h3= link_to_if false, show.name, show_episodes_path(show)
  - if show.unwatched_episode_count > 0
    %p.ui-li-aside
      = show.unwatched_episode_count

app/views/shows/index.html.haml
%ul.horizontal_menu
  %li= link_to "All Shows", shows_path
  %li= link_to "Recent Shows", shows_path(:recent => true)
%hr/
= form_for @search, :url => shows_path, :html => {:method => :get} do |f|
  = f.label :name_contains
  = f.text_field :name_contains
  %br/
  %br/
  / etc...
  = f.submit
%table
  %thead
    %tr
      %th= sort_link @search, :sortable_name, "Name"
      %th= sort_link @search, :unwatched_episode_count
      %th= sort_link @search, :latest_unwatched_episode_at
  %tbody
    = render :partial => "search_results", :locals => {:search_results => collection}

app/views/shows/index.mobile.haml
%ul{"data-role" => "listview", "data-theme" => "d"}
  = render :partial => "show", :collection => collection

app/views/shows/recent.html.haml
= render :partial => "search_results", :locals => {:search_results => @shows}